#!/usr/bin/env bash
# Pick a stable codesigning identity for LiveBlock so macOS TCC keeps the
# Screen Recording / Accessibility grants across rebuilds. Without this
# every Debug build is signed adhoc ("Sign to Run Locally") with a fresh
# cdhash — TCC treats each build as a brand-new app and re-prompts.
#
# Strategy:
#   By default, create a self-signed local cert "LiveBlocker Local Dev" in
#   the login keychain via openssl + security. Self-signed certs produce a
#   stable designated requirement across rebuilds, so TCC keeps the grant.
#   Self-signed works for *anyone* — no Apple Developer membership needed.
#
#   With LB_USE_APPLE_CERT=1, prefer an existing Developer ID Application
#   cert from the keychain instead. This is for users who have a real Mac
#   provisioning profile registered (App Store / signed distribution).
#   Plain "Apple Development" certs are iOS-only on Macs without a profile,
#   so we don't try them automatically.
#
# Output: writes shell `KEY=value` lines to tools/.codesign_identity that
# run.sh sources before invoking xcodebuild. Per-user file, gitignored.
#
# Usage:
#   tools/setup_codesign_identity.sh           # idempotent setup (self-signed)
#   LB_USE_APPLE_CERT=1 tools/setup_codesign_identity.sh   # prefer Apple cert
#   tools/setup_codesign_identity.sh --reset   # delete file + self-signed cert

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$REPO_ROOT/tools/.codesign_identity"
SELF_SIGNED_NAME="LiveBlocker Local Dev"
SELF_SIGNED_KEY_DIR="$HOME/.config/liveblocker"
SELF_SIGNED_KEY="$SELF_SIGNED_KEY_DIR/local-codesign.key"
SELF_SIGNED_CRT="$SELF_SIGNED_KEY_DIR/local-codesign.crt"

if [[ "${1:-}" == "--reset" ]]; then
  rm -f "$OUT"
  security delete-certificate -c "$SELF_SIGNED_NAME" 2>/dev/null || true
  rm -f "$SELF_SIGNED_KEY" "$SELF_SIGNED_CRT"
  echo "Reset complete."
  exit 0
fi

step() { printf '\033[1;34m▸\033[0m %s\n' "$*"; }

# ---------- Path 1: opt-in Developer ID Application cert ----------
#
# Only honored when LB_USE_APPLE_CERT=1 since plain "Apple Development"
# certs without a registered Mac provisioning profile fail to sign mac
# apps with "No Mac Development signing certificate ... was found".

if [[ "${LB_USE_APPLE_CERT:-}" == "1" ]]; then
  step "Scanning login keychain for Developer ID Application certs..."
  identities="$(security find-identity -v -p codesigning login.keychain 2>/dev/null \
    || security find-identity -v -p codesigning 2>/dev/null || true)"
  apple_line="$(echo "$identities" \
    | grep -E '"Developer ID Application' | head -1 || true)"
  if [[ -n "$apple_line" ]]; then
    hash="$(echo "$apple_line" | awk '{print $2}')"
    name="$(echo "$apple_line" | sed -E 's/^[^"]*"([^"]+)"$/\1/')"
    team="$(echo "$name" | sed -nE 's/.*\(([A-Z0-9]{10})\)$/\1/p')"
    step "Using Apple-issued identity: $name"
    cat > "$OUT" <<EOF
# Generated by tools/setup_codesign_identity.sh — do not edit by hand.
LB_CODESIGN_IDENTITY="$name"
LB_CODESIGN_HASH="$hash"
LB_DEVELOPMENT_TEAM="$team"
EOF
    echo "Wrote $OUT"
    exit 0
  fi
  echo "  (no Developer ID Application cert found; falling through to self-signed)"
fi

# ---------- Path 2: self-signed local cert (default) ----------

step "Setting up self-signed local identity..."

mkdir -p "$SELF_SIGNED_KEY_DIR"
chmod 700 "$SELF_SIGNED_KEY_DIR"

# Skip generation if we already have one in the keychain.
if security find-certificate -c "$SELF_SIGNED_NAME" >/dev/null 2>&1; then
  step "Existing self-signed cert found: $SELF_SIGNED_NAME"
else
  step "Generating RSA 2048 keypair..."
  openssl genrsa -out "$SELF_SIGNED_KEY" 2048

  step "Generating self-signed X.509 cert valid for 10 years..."
  # `basicConstraints=CA:false` + the codeSigning EKU lets `find-identity`
  # surface the cert under the `-p codesigning` policy. Without these the
  # keychain holds the cert + key but they aren't linked into an "identity".
  openssl req -x509 -new -key "$SELF_SIGNED_KEY" -out "$SELF_SIGNED_CRT" \
    -days 3650 -subj "/CN=$SELF_SIGNED_NAME" \
    -addext "basicConstraints=critical,CA:false" \
    -addext "extendedKeyUsage=critical,codeSigning" \
    -addext "keyUsage=critical,digitalSignature"

  # Bundle into a .p12 so `security import` links cert+key into one identity.
  # macOS's `security import` is picky about empty .p12 passwords, so use a
  # fixed throwaway password and pass it through. The .p12 is deleted after.
  P12="$SELF_SIGNED_KEY_DIR/local-codesign.p12"
  P12_PASS="liveblocker-local"
  step "Bundling into PKCS#12..."
  openssl pkcs12 -export \
    -out "$P12" \
    -inkey "$SELF_SIGNED_KEY" \
    -in "$SELF_SIGNED_CRT" \
    -name "$SELF_SIGNED_NAME" \
    -passout "pass:$P12_PASS" \
    -legacy 2>/dev/null \
    || openssl pkcs12 -export \
        -out "$P12" \
        -inkey "$SELF_SIGNED_KEY" \
        -in "$SELF_SIGNED_CRT" \
        -name "$SELF_SIGNED_NAME" \
        -passout "pass:$P12_PASS"

  step "Importing identity into login keychain..."
  security import "$P12" -k login.keychain -P "$P12_PASS" \
    -T /usr/bin/codesign -T /usr/bin/security -A

  # Mark the self-signed cert as trusted for code signing so `codesign`
  # accepts it without complaint. -d adds to the user (admin) trust domain.
  step "Trusting cert for code signing..."
  security add-trusted-cert -d -r trustAsRoot -p codeSign \
    -k login.keychain "$SELF_SIGNED_CRT" 2>/dev/null \
    || security add-trusted-cert -r trustAsRoot -p codeSign \
        -k login.keychain "$SELF_SIGNED_CRT" 2>/dev/null \
    || true

  # Whitelist `codesign` so it can use the key without password prompts.
  security set-key-partition-list -S apple-tool:,apple:,codesign: \
    -s -k "" login.keychain >/dev/null 2>&1 || true

  rm -f "$P12"
fi

# `security find-identity -p codesigning` doesn't always surface self-signed
# certs even when codesign(1) accepts them. Verify by actually signing a
# throwaway binary instead.
PROBE_BIN="$(mktemp)"
printf '\xcf\xfa\xed\xfe' >"$PROBE_BIN"
if ! codesign --sign "$SELF_SIGNED_NAME" --force --timestamp=none "$PROBE_BIN" 2>/dev/null; then
  rm -f "$PROBE_BIN"
  echo "Error: codesign cannot use \"$SELF_SIGNED_NAME\". Try --reset and rerun." >&2
  exit 1
fi
rm -f "$PROBE_BIN"

# Pull the cert's SHA-1 so future passes know what's wired up.
hash="$(security find-certificate -c "$SELF_SIGNED_NAME" -Z login.keychain 2>/dev/null \
  | awk '/SHA-1 hash:/ {print $3; exit}')"

cat > "$OUT" <<EOF
# Generated by tools/setup_codesign_identity.sh — do not edit by hand.
# Self-signed local identity. Stable across rebuilds → TCC remembers grants.
LB_CODESIGN_IDENTITY="$SELF_SIGNED_NAME"
LB_CODESIGN_HASH="$hash"
LB_DEVELOPMENT_TEAM=""
EOF

step "Wrote $OUT"
echo
echo "Done. Run \`./run.sh\` and grant Screen Recording once — future rebuilds"
echo "will keep the grant because the signature stays the same."
